# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BackgroundCountdown(object):
    def setupUi(self, BackgroundCountdown):
        BackgroundCountdown.setObjectName("BackgroundCountdown")
        BackgroundCountdown.resize(735, 476)
        self.centralwidget = QtWidgets.QWidget(BackgroundCountdown)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 131, 17))
        self.label_3.setObjectName("label_3")
        self.choosefileButton = QtWidgets.QPushButton(self.centralwidget)
        self.choosefileButton.setGeometry(QtCore.QRect(10, 49, 131, 25))
        self.choosefileButton.setStyleSheet("\n"
"background-color: rgb(255, 255, 255, 50%);")
        self.choosefileButton.setObjectName("choosefileButton")
        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setGeometry(QtCore.QRect(10, 360, 171, 25))
        self.editButton.setStyleSheet("\n"
"background-color: rgb(255, 255, 255, 50%);")
        self.editButton.setObjectName("editButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 19, 231, 17))
        self.label_2.setObjectName("label_2")
        self.positionButton = QtWidgets.QPushButton(self.centralwidget)
        self.positionButton.setGeometry(QtCore.QRect(230, 360, 161, 25))
        self.positionButton.setStyleSheet("\n"
"background-color: rgb(255, 255, 255, 50%);")
        self.positionButton.setObjectName("positionButton")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(10, 390, 171, 25))
        self.deleteButton.setStyleSheet("\n"
"background-color: rgb(255, 255, 255, 50%);")
        self.deleteButton.setObjectName("deleteButton")
        self.createCountdButton = QtWidgets.QPushButton(self.centralwidget)
        self.createCountdButton.setGeometry(QtCore.QRect(10, 180, 141, 25))
        self.createCountdButton.setStyleSheet("\n"
"background-color: rgb(255, 255, 255, 90%);")
        self.createCountdButton.setObjectName("createCountdButton")
        self.fileLabel = QtWidgets.QLabel(self.centralwidget)
        self.fileLabel.setGeometry(QtCore.QRect(160, 49, 231, 25))
        self.fileLabel.setText("")
        self.fileLabel.setObjectName("fileLabel")
        self.itemsList = QtWidgets.QListWidget(self.centralwidget)
        self.itemsList.setGeometry(QtCore.QRect(410, 0, 321, 431))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.itemsList.setFont(font)
        self.itemsList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.itemsList.setObjectName("itemsList")
        self.displayButton = QtWidgets.QPushButton(self.centralwidget)
        self.displayButton.setGeometry(QtCore.QRect(230, 390, 161, 25))
        self.displayButton.setStyleSheet("\n"
"background-color: rgb(255, 255, 255, 50%);")
        self.displayButton.setObjectName("displayButton")
        self.resetImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetImageButton.setGeometry(QtCore.QRect(370, 50, 22, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resetImageButton.setFont(font)
        self.resetImageButton.setStyleSheet("color: rgb(164, 0, 0);\n"
"background-color: rgb(255, 255, 255, 50%);\n"
"border-color: rgb(243, 243, 243, 0%);")
        self.resetImageButton.setObjectName("resetImageButton")
        self.createTextButton = QtWidgets.QPushButton(self.centralwidget)
        self.createTextButton.setGeometry(QtCore.QRect(10, 150, 141, 25))
        self.createTextButton.setStyleSheet("\n"
"background-color: rgb(255, 255, 255, 90%);")
        self.createTextButton.setObjectName("createTextButton")
        self.createClocksButton = QtWidgets.QPushButton(self.centralwidget)
        self.createClocksButton.setGeometry(QtCore.QRect(10, 210, 141, 25))
        self.createClocksButton.setStyleSheet("\n"
"background-color: rgb(255, 255, 255, 90%);")
        self.createClocksButton.setObjectName("createClocksButton")
        BackgroundCountdown.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BackgroundCountdown)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 735, 22))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        BackgroundCountdown.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BackgroundCountdown)
        self.statusbar.setObjectName("statusbar")
        BackgroundCountdown.setStatusBar(self.statusbar)
        self.actionImport = QtWidgets.QAction(BackgroundCountdown)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(BackgroundCountdown)
        self.actionExport.setObjectName("actionExport")
        self.actionSettings = QtWidgets.QAction(BackgroundCountdown)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAbout = QtWidgets.QAction(BackgroundCountdown)
        self.actionAbout.setObjectName("actionAbout")
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionExport)
        self.menuSettings.addAction(self.actionImport)
        self.menuSettings.addAction(self.actionSettings)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(BackgroundCountdown)
        self.deleteButton.clicked.connect(BackgroundCountdown.delete_item_slot)
        self.choosefileButton.clicked.connect(BackgroundCountdown.choose_file_slot)
        self.editButton.clicked.connect(BackgroundCountdown.edit_item_slot)
        self.positionButton.clicked.connect(BackgroundCountdown.position_item_slot)
        self.displayButton.clicked.connect(BackgroundCountdown.display_layout_slot)
        self.resetImageButton.clicked.connect(BackgroundCountdown.reset_image_slot)
        self.itemsList.doubleClicked['QModelIndex'].connect(BackgroundCountdown.edit_item_slot)
        self.createCountdButton.clicked.connect(BackgroundCountdown.create_countdown_slot)
        self.createTextButton.clicked.connect(BackgroundCountdown.create_text_slot)
        self.createClocksButton.clicked.connect(BackgroundCountdown.create_clocks_slot)
        self.actionExport.triggered.connect(BackgroundCountdown.action_export_slot)
        self.actionImport.triggered.connect(BackgroundCountdown.action_import_slot)
        self.actionSettings.triggered.connect(BackgroundCountdown.action_settings_slot)
        self.actionAbout.triggered.connect(BackgroundCountdown.action_about_slot)
        QtCore.QMetaObject.connectSlotsByName(BackgroundCountdown)

    def retranslateUi(self, BackgroundCountdown):
        _translate = QtCore.QCoreApplication.translate
        BackgroundCountdown.setWindowTitle(_translate("BackgroundCountdown", "CountDown & More"))
        self.label_3.setText(_translate("BackgroundCountdown", "Create elements"))
        self.choosefileButton.setText(_translate("BackgroundCountdown", "Choose a file"))
        self.editButton.setText(_translate("BackgroundCountdown", "Edit"))
        self.label_2.setText(_translate("BackgroundCountdown", "Background"))
        self.positionButton.setText(_translate("BackgroundCountdown", "Position Item"))
        self.deleteButton.setText(_translate("BackgroundCountdown", "Delete"))
        self.createCountdButton.setText(_translate("BackgroundCountdown", "Countdown"))
        self.displayButton.setText(_translate("BackgroundCountdown", "Display Layout"))
        self.resetImageButton.setText(_translate("BackgroundCountdown", "X"))
        self.createTextButton.setText(_translate("BackgroundCountdown", "Text"))
        self.createClocksButton.setText(_translate("BackgroundCountdown", "Clocks"))
        self.menuSettings.setTitle(_translate("BackgroundCountdown", "Menu"))
        self.actionImport.setText(_translate("BackgroundCountdown", "Import"))
        self.actionExport.setText(_translate("BackgroundCountdown", "Export"))
        self.actionSettings.setText(_translate("BackgroundCountdown", "Settings"))
        self.actionAbout.setText(_translate("BackgroundCountdown", "About"))

