# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PositionLayout.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PositionLayout(object):
    def setupUi(self, PositionLayout):
        PositionLayout.setObjectName("PositionLayout")
        PositionLayout.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(PositionLayout)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 151, 431))
        self.widget.setAutoFillBackground(True)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 112, 144))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setContentsMargins(6, 3, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.centerRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.centerRadioButton.setStyleSheet("")
        self.centerRadioButton.setObjectName("centerRadioButton")
        self.verticalLayout.addWidget(self.centerRadioButton)
        self.leftUpRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.leftUpRadioButton.setStyleSheet("")
        self.leftUpRadioButton.setObjectName("leftUpRadioButton")
        self.verticalLayout.addWidget(self.leftUpRadioButton)
        self.leftDownRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.leftDownRadioButton.setStyleSheet("")
        self.leftDownRadioButton.setObjectName("leftDownRadioButton")
        self.verticalLayout.addWidget(self.leftDownRadioButton)
        self.rightUpRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rightUpRadioButton.setStyleSheet("")
        self.rightUpRadioButton.setObjectName("rightUpRadioButton")
        self.verticalLayout.addWidget(self.rightUpRadioButton)
        self.rightDownRadioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rightDownRadioButton.setStyleSheet("")
        self.rightDownRadioButton.setObjectName("rightDownRadioButton")
        self.verticalLayout.addWidget(self.rightDownRadioButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_2.setEnabled(True)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 140, 141, 129))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.AxisLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.AxisLayout.setContentsMargins(5, 0, 0, 0)
        self.AxisLayout.setObjectName("AxisLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setEnabled(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.XAxisSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.XAxisSpinBox.setDecimals(1)
        self.XAxisSpinBox.setMaximum(9999.0)
        self.XAxisSpinBox.setSingleStep(5.0)
        self.XAxisSpinBox.setObjectName("XAxisSpinBox")
        self.horizontalLayout.addWidget(self.XAxisSpinBox)
        self.AxisLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setEnabled(True)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.YAxisSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.YAxisSpinBox.setDecimals(1)
        self.YAxisSpinBox.setMaximum(9999.0)
        self.YAxisSpinBox.setSingleStep(5.0)
        self.YAxisSpinBox.setObjectName("YAxisSpinBox")
        self.horizontalLayout_2.addWidget(self.YAxisSpinBox)
        self.AxisLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.sizeSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.sizeSpinBox.setMaximum(9999)
        self.sizeSpinBox.setProperty("value", 30)
        self.sizeSpinBox.setObjectName("sizeSpinBox")
        self.horizontalLayout_3.addWidget(self.sizeSpinBox)
        self.AxisLayout.addLayout(self.horizontalLayout_3)
        self.fontComboBox = QtWidgets.QFontComboBox(self.widget)
        self.fontComboBox.setGeometry(QtCore.QRect(5, 296, 136, 31))
        self.fontComboBox.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"border-color: rgb(238, 238, 236);")
        self.fontComboBox.setObjectName("fontComboBox")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 330, 121, 83))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_2.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.boldCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.boldCheckBox.setFont(font)
        self.boldCheckBox.setObjectName("boldCheckBox")
        self.verticalLayout_2.addWidget(self.boldCheckBox)
        self.italicCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.italicCheckBox.setFont(font)
        self.italicCheckBox.setObjectName("italicCheckBox")
        self.verticalLayout_2.addWidget(self.italicCheckBox)
        self.underlineCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.underlineCheckBox.setFont(font)
        self.underlineCheckBox.setObjectName("underlineCheckBox")
        self.verticalLayout_2.addWidget(self.underlineCheckBox)
        self.colorBotton = QtWidgets.QPushButton(self.widget)
        self.colorBotton.setGeometry(QtCore.QRect(5, 270, 17, 17))
        self.colorBotton.setText("")
        self.colorBotton.setObjectName("colorBotton")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(30, 270, 81, 17))
        self.label_4.setObjectName("label_4")
        PositionLayout.setCentralWidget(self.centralwidget)

        self.retranslateUi(PositionLayout)
        self.centerRadioButton.clicked.connect(PositionLayout.center_slot)
        self.leftUpRadioButton.clicked.connect(PositionLayout.left_up_slot)
        self.rightUpRadioButton.clicked.connect(PositionLayout.right_up_slot)
        self.rightDownRadioButton.clicked.connect(PositionLayout.right_down_slot)
        self.leftDownRadioButton.clicked.connect(PositionLayout.left_down_slot)
        self.sizeSpinBox.valueChanged['int'].connect(PositionLayout.update_font_slot)
        self.fontComboBox.currentFontChanged['QFont'].connect(PositionLayout.update_font_slot)
        self.boldCheckBox.clicked.connect(PositionLayout.update_font_slot)
        self.italicCheckBox.clicked.connect(PositionLayout.update_font_slot)
        self.underlineCheckBox.clicked.connect(PositionLayout.update_font_slot)
        self.colorBotton.clicked.connect(PositionLayout.change_color_slot)
        self.XAxisSpinBox.valueChanged['double'].connect(PositionLayout.update_X_axis_slot)
        self.YAxisSpinBox.valueChanged['double'].connect(PositionLayout.update_Y_axis_slot)
        QtCore.QMetaObject.connectSlotsByName(PositionLayout)

    def retranslateUi(self, PositionLayout):
        _translate = QtCore.QCoreApplication.translate
        PositionLayout.setWindowTitle(_translate("PositionLayout", "Position Layout"))
        self.centerRadioButton.setText(_translate("PositionLayout", "Center"))
        self.leftUpRadioButton.setText(_translate("PositionLayout", "Left up"))
        self.leftDownRadioButton.setText(_translate("PositionLayout", "Left down"))
        self.rightUpRadioButton.setText(_translate("PositionLayout", "Right up"))
        self.rightDownRadioButton.setText(_translate("PositionLayout", "Right down"))
        self.label.setText(_translate("PositionLayout", "X-axis"))
        self.label_2.setText(_translate("PositionLayout", "Y-axis"))
        self.label_3.setText(_translate("PositionLayout", "Size"))
        self.boldCheckBox.setText(_translate("PositionLayout", "Bold"))
        self.italicCheckBox.setText(_translate("PositionLayout", "Italic"))
        self.underlineCheckBox.setText(_translate("PositionLayout", "Underline"))
        self.label_4.setText(_translate("PositionLayout", "Text color"))

